services:
  frigate:
    container_name: frigate
    privileged: true # may not be necessary
    restart: unless-stopped
    stop_grace_period: 30s # alows for graceful service shutdown
    image: ghcr.io/blakeblackshear/frigate:0.16.0
    shm_size: "512mb" # 4x as large as my old setup, should be good
    devices:
      - /dev/bus/usb:/dev/bus/usb # for the coarl tpu
    volumes:
      - /etc/localtime:/etc/localtime:ro # time
      - /mnt/TANK/docker/frigate/config:/config # config
      - /mnt/TANK/docker/frigate/storage:/media/storage # storage
      - type: tmpfs # temporary files
        target: /tmp/cache
        tmpfs:
          size: 1000000000 # 1GB
    ports:
      - "8971:8971" # web authenticated
      - "5000:5000" # web unauthenticated
      - "8554:8554" # RTSP
      - "8555:8555/tcp" # WebRTC over TCP
      - "8555:8555/udp" # WebRTC over UDP
